<%
class TratamentoChar
	public function trataCharPost(auxUsuario)
	
		auxUsuario = replace(auxUsuario,"รก"		,"แ")
		auxUsuario = replace(auxUsuario,"ร "		,"เ")
		auxUsuario = replace(auxUsuario,"รฃ"		,"ใ")
		auxUsuario = replace(auxUsuario,"รข"		,"โ")
		auxUsuario = replace(auxUsuario,"รค"		,"ไ")
		auxUsuario = replace(auxUsuario,"รฉ"		,"้")
		auxUsuario = replace(auxUsuario,"รจ"		,"่")
		auxUsuario = replace(auxUsuario,"รช"		,"๊")
		auxUsuario = replace(auxUsuario,"รซ"		,"๋")
		auxUsuario = replace(auxUsuario,"รญ"		,"ํ") 
		auxUsuario = replace(auxUsuario,"รฌ"		,"์")
		auxUsuario = replace(auxUsuario,"รฎ"		,"๎")
		auxUsuario = replace(auxUsuario,"รฏ"		,"๏")
		auxUsuario = replace(auxUsuario,"รณ"		,"๓")
		auxUsuario = replace(auxUsuario,"รฒ"		,"๒")
		auxUsuario = replace(auxUsuario,"รต"		,"๕")
		auxUsuario = replace(auxUsuario,"รด"		,"๔")
		auxUsuario = replace(auxUsuario,"รถ"		,"๖")
		auxUsuario = replace(auxUsuario,"รบ"		,"๚")
		auxUsuario = replace(auxUsuario,"รน"		,"๙")
		auxUsuario = replace(auxUsuario,"รป"		,"๛")
		auxUsuario = replace(auxUsuario,"รผ"		,"ü")
		auxUsuario = replace(auxUsuario,"รง"		,"็")
		auxUsuario = replace(auxUsuario,"รฑ"		,"๑")
		auxUsuario = replace(auxUsuario,"รฝ"		,"ý")
		auxUsuario = replace(auxUsuario,"รฟ"		,"ÿ")
		auxUsuario = replace(auxUsuario,"ร"		,"ว")
		auxUsuario = replace(auxUsuario,"ร"		,"ร")
		auxUsuario = replace(auxUsuario,"ร•"		,"ี")
		auxUsuario = replace(auxUsuario,"ฤ"		,"ศ")
		auxUsuario = replace(auxUsuario,"ร"		,"ษ")
		auxUsuario = replace(auxUsuario,"ยบ"		,"บ")
		auxUsuario = replace(auxUsuario,"ยฐ"		,"ฐ")
		auxUsuario = replace(auxUsuario,"ร"		,"อ")
		auxUsuario = replace(auxUsuario,"โ€“"		,"-")
		auxUsuario = replace(auxUsuario,"ร€"		,"ภ")	
		'auxUsuario = replace(auxUsuario,"ร"		    ,"ม")
		auxUsuario = replace(auxUsuario,"ม"	    ,"ย")
		auxUsuario = replace(auxUsuario,"ม"	    ,"ย")
		auxUsuario = replace(auxUsuario,"ม”"	    ,"ิ")
		auxUsuario = replace(auxUsuario,"ม"	    ,"ฺ")
		auxUsuario = replace(auxUsuario,"ยช"	    ,"ช")
		auxUsuario = replace(auxUsuario,"ร“"		,"ำ")

		trataCharPost = auxUsuario
		
	end function	
end class
%>